// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVSNfHjcpvE7zJXmULyR3Y-XoqDb6uewk',
    appId: '1:564545876969:web:9409487e962e2de6829178',
    messagingSenderId: '564545876969',
    projectId: 'video-share-9759d',
    authDomain: 'video-share-9759d.firebaseapp.com',
    storageBucket: 'video-share-9759d.appspot.com',
    measurementId: 'G-4DGFKN5GZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVldyF-Q3oV1QIAgmg4ztaeu2YazX929o',
    appId: '1:564545876969:android:0ea7101ea90a6d10829178',
    messagingSenderId: '564545876969',
    projectId: 'video-share-9759d',
    storageBucket: 'video-share-9759d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPqWbCGvQj4knoYaBf-kLPd4gAaCS73fg',
    appId: '1:564545876969:ios:61a458a488e6173d829178',
    messagingSenderId: '564545876969',
    projectId: 'video-share-9759d',
    storageBucket: 'video-share-9759d.appspot.com',
    iosBundleId: 'com.ahmadhabibshovo.videoSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPqWbCGvQj4knoYaBf-kLPd4gAaCS73fg',
    appId: '1:564545876969:ios:bd281fb3da7e1408829178',
    messagingSenderId: '564545876969',
    projectId: 'video-share-9759d',
    storageBucket: 'video-share-9759d.appspot.com',
    iosBundleId: 'com.ahmadhabibshovo.videoSharingApp.RunnerTests',
  );
}
